## Sztuczne sieci neuronowe - laboratorium 1

## Marcin Ogórkiewicz

### NumPy - powtórzenie
Podstawową strukturą w NumPy jest tablica wielowymiarowa: n-dimensional array (ndarray):
- przechowuje elementy określonego typu
- typowo elementy zajmują sąsiednie bloki w pamięci

Dzięki temu jest ona szybsza niż standardowa lista w

In [155]:
import numpy as np
import pandas as pd

#### Ćwiczenie

Niech `a = np.array([0, 1, 2, 3])`.

Jaki będzie rezultat poniższych wywołań?
- `type(a)`
- `a.dtype`
- `a.shape`
- `a.ndim`

In [156]:
a = np.array([0, 1, 2, 3])

In [157]:
print(type(a)) # Wyświetla typ zmiennej a
print(a.dtype) # Wyświetla typ danych w tablicy
print(a.shape) # Wyświetla kształt tablicy
print(a.ndim) # Wyświetla ilość wymiarów tablicy

<class 'numpy.ndarray'>
int64
(4,)
1


### Ćwiczenie

Niech `a = np.array([1, 2, 3, 4])` i `b = np.array([2, 3, 4, 5])`.

Jaki będzie rezultat poniższych wywołań?

- `a + b`
- `a * b`
- `a ** b`

In [158]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [159]:
print(a + b) # Dodawanie
print(a * b) # Mnożenie elementów
print(a ** b) # Potęgowanie elementów

[3 5 7 9]
[ 2  6 12 20]
[   1    8   81 1024]


### Ćwiczenie

Niech `a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])`

Jaki będzie rezultat poniższych wywołań?
- `a.shape`
- `a.size`
- `a.ndim`
- `a[1]`

In [160]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])

In [161]:
print(a.shape) # Wyświetla kształt tablicy
print(a.size) # Wyświetla ilość elementów w tablicy 2x4
print(a.ndim) # Wyświetla ilość wymiarów tablicy
a[1] # Wyświetla drugi wiersz tablicy

(2, 4)
8
2


array([10, 11, 12, 13])

### Ćwiczenie

Niech `a = np.array([10,11,12,13,14])`

Jaki będzie rezultat poniższych wywołań?
- `a[1:3]`
- `a[1:-2]`
- `a[:3]`
- `a[-2:]`
- `a[::2]`

In [162]:
a = np.array([10,11,12,13,14])

In [163]:
print(a[1:3]) # Wyświetla elementy od 1 do 3
print(a[1:-2]) # Wyświetla elementy od 1 do przedostatniego
print(a[:3]) # Wyświetla elementy od początku do 3
print(a[-2:]) # Wyświetla dwa ostatnie elementy
print(a[::2]) # Wyświetla co drugi element

[11 12]
[11 12]
[10 11 12]
[13 14]
[10 12 14]


### Ćwiczenie

Niech `a = np.array([0, 1, 2, 3, 4])`.
Jaka (i dlaczego) będzie zawartość `a` po wywołaniu kolejno:
- `b = a[2:4]`
- `b[0] = 10` ?

In [164]:
a = np.array([0, 1, 2, 3, 4])

In [165]:
b=a[2:4] # Przypisuje do b elementy od 2 do 4
b[0] = 10 # Zmienia pierwszy element b na 10
b # Wyświetla tablicę b

array([10,  3])

### Ćwiczenie

Jaka będzie zawartość `b` po wywołaniu kolejno:
- `a = np.arange(0, 80, 10)`
- `mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)`
- `b = a[mask]` ?


In [166]:
a=np.arange(0,80,10) # Tworzy tablicę od 0 do 80 co 10
mask=np.array([0,1,1,0,0,1,0,0], dtype=bool) # Tworzy maskę
b=a[mask] # Przypisuje do b elementy z tablicy a, które są zaznaczone w masce
a,b # Wyświetla tablicę a i b

(array([ 0, 10, 20, 30, 40, 50, 60, 70]), array([10, 20, 50]))

### Ćwiczenie

Niech `a = np.array([[1, 2, 3], [4, 5, 6]])`

Jaki będzie rezultat poniższych wywołań:
- `a.sum()`
- `a.sum(axis=0)`
- `a.sum(axis=-1)`
- `np.max(a, axis=1)`
- `np.argmax(a, axis=1)`
- `np.mean(a, axis=0)`

In [167]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [168]:
print(a.sum()) # Sumuje wszystkie elementy tablicy
print(a.sum(axis=0)) # Sumuje elementy w kolumnach
print(a.sum(axis=-1)) # Sumuje elementy w wierszach
print(np.max(a, axis=1)) # Znajduje maksimum w wierszach
print(np.argmax(a, axis=1)) # Znajduje indeks maksimum w wierszach
print(np.mean(a, axis=0)) # Oblicza średnią w kolumnach

21
[5 7 9]
[ 6 15]
[3 6]
[2 2]
[2.5 3.5 4.5]


### Ćwiczenie

Jaka (i dlaczego) będzie zawartość zmiennej `b` po wywołaniu kolejno poniższych komend?

- `a = np.arange(-2, 2) ** 2`
- `mask = a % 2 == 0`
- `b = np.where(mask)`

In [169]:
a = np.arange(-2,2) ** 2 # Tworzy tablicę od -2 do 2 i podnosi do kwadratu
mask = a % 2 == 0 # Tworzy maskę, która zaznacza elementy parzyste
b = np.where(mask) # Zwraca indeksy elementów spełniających warunek
a,b

(array([4, 1, 0, 1]), (array([0, 2]),))

### Ćwiczenie

Niech `a = np.array([1, 0, 0, 1])` i `b = np.array([1, 2, 3, 4])`

Jaki będzie rezultat wywołania `np.dot(a, b)`?

In [170]:
a = np.array([1, 0, 0, 1])
b = np.array([1, 2, 3, 4])

In [171]:
np.dot(a, b) # Iloczyn skalarny dwóch wektorów

np.int64(5)

### Ćwiczenie

Niech `a = np.array([[1, 0], [0, 1]])` i `b = np.array([[1, 2], [3, 4]])`

Jaki będzie rezultat wywołania `np.dot(a, b)`?

In [172]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

In [173]:
np.dot(a, b) # Iloczyn macierzy

array([[1, 2],
       [3, 4]])

### Ćwiczenie
Niech `a = np.array([[1, 2, 3], [4, 5, 6]])`.

Jaki będzie rezultat wywołania `np.transpose(a)` (lub `a.T`)?

In [174]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(a) # Transponuje macierz

array([[1, 4],
       [2, 5],
       [3, 6]])

### PyTorch - podstawy
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [175]:
import torch

W PyTorch podstawową strukturą, analogiczną do `np.array` jest tensor (`torch.Tensor`). Można go zaincjalizować na kilka sposobów, np.:

1) z listy list
```
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
```

2) z np.array
```
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# w drugą stronę: x_np.numpy() pozwala na konwersję Tensora do numpy
# uwaga: np array oraz tensor współdzielą pamięć i zmiany w jednym obiekcie spowodują zmiany w drugim
```

3) z użyciem wbudowanych funkcji (np. rand, zeros, ones)

```
shape = (2, 3,)
rand_tensor = torch.rand(shape)
```

Tensor posiada takie atrybuty, jak:
- shape - krotka (tuple) opisująca jego wymiary
- dtype - przechowyway typ danych
- device - domyślnie `cpu`

Jeśli posiadamy kartę graficzną, możemy sprawdzić, czy jest "wykryta" przez PyTorch: `torch.cuda.is_available()`.
Jeśli tak, możemy dla przyspieszenia obliczeń przenieść tensor na GPU: `tensor = tensor.to('cuda')`

### Ćwiczenie

Stwórz tensor rozmiaru `(3, 2)` zainicjalizowany liczbami losowymi. Sprawdź typ stworzonego obiektu, typ przechowywanych danych oraz atrybuty `shape` i `device`. Jeśli posiadasz kartę graficzną obsługującą CUDA, spróbuj przenieść na nią stworzony tensor.

In [176]:
torch.cuda.is_available() # Sprawdza czy dostępna jest karta graficzna

False

In [177]:
a = torch.rand(3,2)
a

tensor([[0.6850, 0.5178],
        [0.1024, 0.4627],
        [0.0047, 0.1151]])

### Ćwiczenie
Niech `points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])`

Wypróbuj, korzystając z tego tensora, jak dla tensorów działa indeksowanie i slicing.

Co zwróci `points[0, 1]`? Na wyniku tej operacji wykonaj metodę `.item()`.

In [178]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [179]:
points[0,1] # Wyświetla element z pierwszego wiersza i drugiej kolumny jako tensor

tensor(1.)

In [180]:
points[0,1].item() # Wyświetla wartość elementu z pierwszego wiersza i drugiej kolumny

1.0

### Ćwiczenie

`torch.cat` i `torch.stack` to funkcje pozwalające łączyć ze sobą tensory. Spróbuj zaobserwować różnicę pomiędzy tymi funkcjami korzystając z kodu poniżej.

In [181]:
t = torch.ones((4, 2))
t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [182]:
t1 = torch.cat([t, t, t], dim=0)
t1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Cat działa podobnie jak w Linux, dokonuje konkatenacji dwóch tensorów.

In [183]:
t2 = torch.stack([t, t, t], dim=0)
t2

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

Spowodowało to połączenie tensorów wzdłuż nowego wymiaru. Efektem jest tensor o rozmiarze 3x4x2

## Wnioski

Laboratorium pozwoliło mi na przypomnienie sobie podstawowych operacji na tablicach w NumPy oraz nauczenie się podstawowych operacji na tensorach w PyTorch. Pozwoliło mi to na przypomnienie sobie jak działa indeksowanie i slicing w tych bibliotekach oraz jakie są różnice między funkcjami `torch.cat` i `torch.stack`.